### ISSUE TITLE
add more properties to channel.spec schema

### ISSUE THREAD

**Issue by Ivshti** [AdExNetwork/adex-validator-stack-js#105]
Suggestions for now; all will be optional, *without* a default value (cause whatever is submitted must be hashed exactly like it is)

* `created` - timestamp of when the channel (and campaign) was created by the user
* a bunch of others from https://github.com/AdExNetwork/adex-protocol/blob/master/campaignSpec.md

**Comment by samparsky** [comment]
@Ivshti This means the properties can't be updated? Or we should pick specific properties that would be used to form the hash?

**Comment by Ivshti** [comment]
@samparsky yeah, the properties in the spec can't be updated cause they're associated by hash to the on-chain `spec`
