### ISSUE TITLE
Implement limits per user, sybil protection (IP, address, PoW, etc.) at a sentry level

### ISSUE THREAD

**Issue by Ivshti** [AdExNetwork/adex-validator-stack-js#21]
in the best case we can do everything through an NGINX config

initial limit ideas:

- [x] event submissions per (channel, publisher) per IP
- [ ] event subimssions per (channel, publisher) per solved memory-bound PoW (Cuckoo Cycle?)

**Comment by samparsky** [comment]
@Ivshti Handling this through NGINX would be much preferable, as it reduces processing from the application layer.
I think openresty can be very suitable for this
