### ISSUE TITLE
DB abstraction

### ISSUE THREAD

**Issue by Ivshti** [AdExNetwork/adex-validator-stack-js#31]
this will help in many ways:

- easy way to get "the latest event of a type"; currently this is used in the follower worker, but it would be useful for #23 too
- allow us to migrate to Postres in v2.0, where we can have static, simple and relational data types (even trees can be stored in a table)
- allow us to abstract away watching for new event aggregates/validator messages, therefore removing wait/snooze periods; under the hood it can be implemented with redis pubsub or via postgres

**Comment by vanina-iv** [comment]
Done: https://medium.com/the-adex-blog/the-adex-protocol-recap-updated-roadmap-inside-3779e6e84e06

**Comment by Ivshti** [comment]
closing in favour of #78
