### ISSUE TITLE
experimental sentry implementation in another lang (e.g. Rust, C, C++)

### ISSUE THREAD

**Issue by Ivshti** [AdExNetwork/adex-validator-stack-js#34]
a sentry subset that only does:

* `/channel/list`
* POST `/channel/:id/events`

-----

the validator stack is architected in such a way that allows easy implementation of an event-only sentry even in ecosystems that don't have good DB drivers/asynchronous IO; this is because we only save 1 eventAggregate every few seconds, and everything else is kept in memory

the purpose of this task would be to see how far we can go performance wise

see #2

**Comment by samparsky** [comment]
@Ivshti I can start work on the Rust implementation. I am quite familiar with Rust.

**Comment by Ivshti** [comment]
closing this for now; will directly move on to a rust re-implementation
